### ISSUE TITLE
Question: How can I spawn multiple dialogs

### ISSUE THREAD

**Issue by didix16** [olton/Metro-UI-CSS#700] opened 2014-12-31 15:29 UTC
Hi again. I'm trying to show multiple dialogs at the same time, but only one is showed... There is some method to show more than one at time? If not, cloud you make capable to show more than one?
Thank you :D

**Comment by vriera** [comment] 2015-01-06 09:29
This question is a duplicate of this one: https://github.com/olton/Metro-UI-CSS/issues/597

**Closed** 2015-04-14 18:29 UTC
