### ISSUE TITLE
Sidebar scrollbars not working in chrome

### ISSUE THREAD

**Issue by dagnelies** [olton/Metro-UI-CSS#1528] opened 2020-05-08 14:20 UTC
Just take chrome and go to https://metroui.org.ua/m4q-about.html

The scrollbar in the side menu is gone. Works on FF and IE though.

**Comment by olton** [comment] 2020-05-08 16:00
crollbar is removed by the css property, ie and ff show it because they do not support the corresponding property

**Comment by dagnelies** [comment] 2020-05-08 18:51
Huh? Why do you remove the scrollbar?! It makes it unusable! You cannot scroll down the side menu! ...or did I understand something wrong?

**Comment by olton** [comment] 2020-05-08 18:56
You can scroll with mouse wheel and touch

**Comment by dagnelies** [comment] 2020-05-09 07:18
Well, without mouse or touch, like a laptop, you're screwed ...I never really understood why people avoid scrollbars

**Comment by olton** [comment] 2020-05-09 07:36
I originally developed Sidebar for another framework - `Core_CSS`. Which was intended for application development in `PhoneGap`. The guideline was taken from the sidebar description for android, where the scroll was not visually displayed. In this form, the component was transferred (together with other components) to `Metro4`. I will add an option to show/hide the scrollbar in 4.3.7 on attribute `data-menu-scrollbar=true|false`.

**Comment by dagnelies** [comment] 2020-05-09 12:55
Thanks. That would be useful.

**Closed** 2020-05-17 17:10 UTC
Labels: enhancement
